### ISSUE TITLE
Privacy policy 

### ISSUE THREAD

**Issue by wlwatkins** [codemakerai/codemaker-jetbrains#1]
Hi,

I just got a token code to test your plugin but I wanted to know what was the privacy policy of codemaker ai. Do you collect, store data? Snippets of code specifically? Where can I find this information?

On your website it simply says 

> Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.

Without any link or more information that I could find. Thanks

**Comment by jmnarloch** [comment]
Thank you for taking time to raise this question.

At CodeMaker AI we treat both the privacy and security seriously. At any point does CodeMaker services collect, aggregate or analyze user provided data for any other purposes than fulfilling the user requested action. Once the processing is completed the user input is deleted from the system and is not stored afterwards in any form. CodeMaker also does not use the user input as training data set, so that it would be then replayed to other user upon same or similar prompt. 

From security perspective all data that is passed through the system is encrypted across entire communication with the service. Each of request is also strictly tied through API Key with single authenticated user making it impossible to access any other user processing results.

We will address the aspect of Privacy Policy and publish it shortly.

**Comment by jmnarloch** [comment]
Thank you for your patience as we were resolving this issue. The Privacy Policy has been publish on the company website and is available at: https://beta.codemaker.ai/privacy-policy
